trigger:
  - main

pool:
  name: Self-Hosted

steps:
  - script: |
      if ! command -v terraform &> /dev/null; then
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        sudo apt update && sudo apt install terraform -y
      fi
    displayName: "Ensure Terraform is Installed"

  - script: |
      terraform init
    displayName: "Initialize Terraform"

  - script: |
      terraform validate
    displayName: "Validate Terraform Code"

  - script: |
      terraform plan -out=tfplan
    displayName: "Plan Terraform Changes"

  - script: |
      terraform apply -auto-approve
    displayName: "Apply Terraform Changes"
