trigger:
  - main

pool:
  name: Self-Hosted

steps:
  - task: PowerShell@2
    displayName: "Ensure Terraform is Installed (Windows)"
    condition: eq( variables['Agent.OS'], 'Windows_NT' )
    inputs:
      targetType: 'inline'
      script: |
        $terraform = terraform -version 2>$null
        if ($terraform -eq $null) {
          Write-Host "Terraform not found. Installing..."
          Invoke-WebRequest -Uri "https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_windows_amd64.zip" -OutFile "terraform.zip"
          Expand-Archive terraform.zip -DestinationPath "C:\terraform"
          [System.Environment]::SetEnvironmentVariable("Path", $env:Path + ";C:\terraform", [System.EnvironmentVariableTarget]::Machine)
          Write-Host "Terraform installed successfully."
        } else {
          Write-Host "Terraform is already installed."
        }

  - script: |
      cd terraform  # Change directory to where .tf files exist
      terraform init
    displayName: "Initialize Terraform"
  
  - script: |
      cd terraform
      terraform validate
    displayName: "Validate Terraform Code"
  
  - script: |
      cd terraform
      terraform plan -out=tfplan
    displayName: "Plan Terraform Changes"
  
  - script: |
      cd terraform
      terraform apply -auto-approve
    displayName: "Apply Terraform Changes"
